INSERT INTO country (cca2, cca3, name_common, name_official, capital, region, subregion, lat, lng, flag) VALUES
('AW', 'ABW', 'Aruba', 'Aruba', '[Oranjestad]', 'Americas', 'Caribbean', 12.5, -69.96666666, '🇦🇼'),
('AF', 'AFG', 'Afghanistan', 'Islamic Republic of Afghanistan', '[Kabul]', 'Asia', 'Southern Asia', 33.0, 65.0, '🇦🇫'),
('AO', 'AGO', 'Angola', 'Republic of Angola', '[Luanda]', 'Africa', 'Middle Africa', -12.5, 18.5, '🇦🇴'),
('AI', 'AIA', 'Anguilla', 'Anguilla', '[The Valley]', 'Americas', 'Caribbean', 18.25, -63.16666666, '🇦🇮'),
('AX', 'ALA', 'Åland Islands', 'Åland Islands', '[Mariehamn]', 'Europe', 'Northern Europe', 60.116667, 19.9, '🇦🇽'),
('AL', 'ALB', 'Albania', 'Republic of Albania', '[Tirana]', 'Europe', 'Southeast Europe', 41.0, 20.0, '🇦🇱'),
('AD', 'AND', 'Andorra', 'Principality of Andorra', '[Andorra la Vella]', 'Europe', 'Southern Europe', 42.5, 1.5, '🇦🇩'),
('AE', 'ARE', 'United Arab Emirates', 'United Arab Emirates', '[Abu Dhabi]', 'Asia', 'Western Asia', 24.0, 54.0, '🇦🇪'),
('AR', 'ARG', 'Argentina', 'Argentine Republic', '[Buenos Aires]', 'Americas', 'South America', -34.0, -64.0, '🇦🇷'),
('AM', 'ARM', 'Armenia', 'Republic of Armenia', '[Yerevan]', 'Asia', 'Western Asia', 40.0, 45.0, '🇦🇲'),
('AS', 'ASM', 'American Samoa', 'American Samoa', '[Pago Pago]', 'Oceania', 'Polynesia', -14.33333333, -170.0, '🇦🇸'),
('AQ', 'ATA', 'Antarctica', 'Antarctica', '[]', 'Antarctic', '', -90.0, 0.0, '🇦🇶'),
('TF', 'ATF', 'French Southern and Antarctic Lands', 'Territory of the French Southern and Antarctic Lands', '[Port-aux-Français]', 'Antarctic', '', -49.25, 69.167, '🇹🇫'),
('AG', 'ATG', 'Antigua and Barbuda', 'Antigua and Barbuda', '[Saint John''s]', 'Americas', 'Caribbean', 17.05, -61.8, '🇦🇬'),
('AU', 'AUS', 'Australia', 'Commonwealth of Australia', '[Canberra]', 'Oceania', 'Australia and New Zealand', -27.0, 133.0, '🇦🇺'),
('AT', 'AUT', 'Austria', 'Republic of Austria', '[Vienna]', 'Europe', 'Central Europe', 47.33333333, 13.33333333, '🇦🇹'),
('AZ', 'AZE', 'Azerbaijan', 'Republic of Azerbaijan', '[Baku]', 'Asia', 'Western Asia', 40.5, 47.5, '🇦🇿'),
('BI', 'BDI', 'Burundi', 'Republic of Burundi', '[Gitega]', 'Africa', 'Eastern Africa', -3.5, 30.0, '🇧🇮'),
('BE', 'BEL', 'Belgium', 'Kingdom of Belgium', '[Brussels]', 'Europe', 'Western Europe', 50.83333333, 4.0, '🇧🇪'),
('BJ', 'BEN', 'Benin', 'Republic of Benin', '[Porto-Novo]', 'Africa', 'Western Africa', 9.5, 2.25, '🇧🇯'),
('BF', 'BFA', 'Burkina Faso', 'Burkina Faso', '[Ouagadougou]', 'Africa', 'Western Africa', 13.0, -2.0, '🇧🇫'),
('BD', 'BGD', 'Bangladesh', 'People''s Republic of Bangladesh', '[Dhaka]', 'Asia', 'Southern Asia', 24.0, 90.0, '🇧🇩'),
('BG', 'BGR', 'Bulgaria', 'Republic of Bulgaria', '[Sofia]', 'Europe', 'Southeast Europe', 43.0, 25.0, '🇧🇬'),
('BH', 'BHR', 'Bahrain', 'Kingdom of Bahrain', '[Manama]', 'Asia', 'Western Asia', 26.0, 50.55, '🇧🇭'),
('BS', 'BHS', 'Bahamas', 'Commonwealth of the Bahamas', '[Nassau]', 'Americas', 'Caribbean', 24.25, -76.0, '🇧🇸'),
('BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', '[Sarajevo]', 'Europe', 'Southeast Europe', 44.0, 18.0, '🇧🇦'),
('BL', 'BLM', 'Saint Barthélemy', 'Collectivity of Saint Barthélemy', '[Gustavia]', 'Americas', 'Caribbean', 18.5, -63.41666666, '🇧🇱'),
('SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', '[Jamestown]', 'Africa', 'Western Africa', -15.95, -5.72, '🇸🇭'),
('BY', 'BLR', 'Belarus', 'Republic of Belarus', '[Minsk]', 'Europe', 'Eastern Europe', 53.0, 28.0, '🇧🇾'),
('BZ', 'BLZ', 'Belize', 'Belize', '[Belmopan]', 'Americas', 'Central America', 17.25, -88.75, '🇧🇿'),
('BM', 'BMU', 'Bermuda', 'Bermuda', '[Hamilton]', 'Americas', 'North America', 32.33333333, -64.75, '🇧🇲'),
('BO', 'BOL', 'Bolivia', 'Plurinational State of Bolivia', '[Sucre]', 'Americas', 'South America', -17.0, -65.0, '🇧🇴'),
('BQ', 'BES', 'Caribbean Netherlands', 'Bonaire, Sint Eustatius and Saba', '[Kralendijk, Oranjestad, The Bottom]', 'Americas', 'Caribbean', 12.18, -68.25, ''),
('BR', 'BRA', 'Brazil', 'Federative Republic of Brazil', '[Brasília]', 'Americas', 'South America', -10.0, -55.0, '🇧🇷'),
('BB', 'BRB', 'Barbados', 'Barbados', '[Bridgetown]', 'Americas', 'Caribbean', 13.16666666, -59.53333333, '🇧🇧'),
('BN', 'BRN', 'Brunei', 'Nation of Brunei, Abode of Peace', '[Bandar Seri Begawan]', 'Asia', 'South-Eastern Asia', 4.5, 114.66666666, '🇧🇳'),
('BT', 'BTN', 'Bhutan', 'Kingdom of Bhutan', '[Thimphu]', 'Asia', 'Southern Asia', 27.5, 90.5, '🇧🇹'),
('BV', 'BVT', 'Bouvet Island', 'Bouvet Island', '[]', 'Antarctic', '', -54.43333333, 3.4, '🇧🇻'),
('BW', 'BWA', 'Botswana', 'Republic of Botswana', '[Gaborone]', 'Africa', 'Southern Africa', -22.0, 24.0, '🇧🇼'),
('CF', 'CAF', 'Central African Republic', 'Central African Republic', '[Bangui]', 'Africa', 'Middle Africa', 7.0, 21.0, '🇨🇫'),
('CA', 'CAN', 'Canada', 'Canada', '[Ottawa]', 'Americas', 'North America', 60.0, -95.0, '🇨🇦'),
('CC', 'CCK', 'Cocos (Keeling) Islands', 'Territory of the Cocos (Keeling) Islands', '[West Island]', 'Oceania', 'Australia and New Zealand', -12.5, 96.83333333, '🇨🇨'),
('CH', 'CHE', 'Switzerland', 'Swiss Confederation', '[Bern]', 'Europe', 'Western Europe', 47.0, 8.0, '🇨🇭'),
('CL', 'CHL', 'Chile', 'Republic of Chile', '[Santiago]', 'Americas', 'South America', -30.0, -71.0, '🇨🇱'),
('CN', 'CHN', 'China', 'People''s Republic of China', '[Beijing]', 'Asia', 'Eastern Asia', 35.0, 105.0, '🇨🇳'),
('CI', 'CIV', 'Ivory Coast', 'Republic of Côte d''Ivoire', '[Yamoussoukro]', 'Africa', 'Western Africa', 8.0, -5.0, '🇨🇮'),
('CM', 'CMR', 'Cameroon', 'Republic of Cameroon', '[Yaoundé]', 'Africa', 'Middle Africa', 6.0, 12.0, '🇨🇲'),
('CD', 'COD', 'DR Congo', 'Democratic Republic of the Congo', '[Kinshasa]', 'Africa', 'Middle Africa', 0.0, 25.0, '🇨🇩'),
('CG', 'COG', 'Congo', 'Republic of the Congo', '[Brazzaville]', 'Africa', 'Middle Africa', -1.0, 15.0, '🇨🇬'),
('CK', 'COK', 'Cook Islands', 'Cook Islands', '[Avarua]', 'Oceania', 'Polynesia', -21.23333333, -159.76666666, '🇨🇰'),
('CO', 'COL', 'Colombia', 'Republic of Colombia', '[Bogotá]', 'Americas', 'South America', 4.0, -72.0, '🇨🇴'),
('KM', 'COM', 'Comoros', 'Union of the Comoros', '[Moroni]', 'Africa', 'Eastern Africa', -12.16666666, 44.25, '🇰🇲'),
('CV', 'CPV', 'Cape Verde', 'Republic of Cabo Verde', '[Praia]', 'Africa', 'Western Africa', 16.0, -24.0, '🇨🇻'),
('CR', 'CRI', 'Costa Rica', 'Republic of Costa Rica', '[San José]', 'Americas', 'Central America', 10.0, -84.0, '🇨🇷'),
('CU', 'CUB', 'Cuba', 'Republic of Cuba', '[Havana]', 'Americas', 'Caribbean', 21.5, -80.0, '🇨🇺'),
('CW', 'CUW', 'Curaçao', 'Country of Curaçao', '[Willemstad]', 'Americas', 'Caribbean', 12.116667, -68.933333, '🇨🇼'),
('CX', 'CXR', 'Christmas Island', 'Territory of Christmas Island', '[Flying Fish Cove]', 'Oceania', 'Australia and New Zealand', -10.5, 105.66666666, '🇨🇽'),
('KY', 'CYM', 'Cayman Islands', 'Cayman Islands', '[George Town]', 'Americas', 'Caribbean', 19.5, -80.5, '🇰🇾'),
('CY', 'CYP', 'Cyprus', 'Republic of Cyprus', '[Nicosia]', 'Europe', 'Southern Europe', 35.0, 33.0, '🇨🇾'),
('CZ', 'CZE', 'Czechia', 'Czech Republic', '[Prague]', 'Europe', 'Central Europe', 49.75, 15.5, '🇨🇿'),
('DE', 'DEU', 'Germany', 'Federal Republic of Germany', '[Berlin]', 'Europe', 'Western Europe', 51.0, 9.0, '🇩🇪'),
('DJ', 'DJI', 'Djibouti', 'Republic of Djibouti', '[Djibouti]', 'Africa', 'Eastern Africa', 11.5, 43.0, '🇩🇯'),
('DM', 'DMA', 'Dominica', 'Commonwealth of Dominica', '[Roseau]', 'Americas', 'Caribbean', 15.41666666, -61.33333333, '🇩🇲'),
('DK', 'DNK', 'Denmark', 'Kingdom of Denmark', '[Copenhagen]', 'Europe', 'Northern Europe', 56.0, 10.0, '🇩🇰'),
('DO', 'DOM', 'Dominican Republic', 'Dominican Republic', '[Santo Domingo]', 'Americas', 'Caribbean', 19.0, -70.66666666, '🇩🇴'),
('DZ', 'DZA', 'Algeria', 'People''s Democratic Republic of Algeria', '[Algiers]', 'Africa', 'Northern Africa', 28.0, 3.0, '🇩🇿'),
('EC', 'ECU', 'Ecuador', 'Republic of Ecuador', '[Quito]', 'Americas', 'South America', -2.0, -77.5, '🇪🇨'),
('EG', 'EGY', 'Egypt', 'Arab Republic of Egypt', '[Cairo]', 'Africa', 'Northern Africa', 27.0, 30.0, '🇪🇬'),
('ER', 'ERI', 'Eritrea', 'State of Eritrea', '[Asmara]', 'Africa', 'Eastern Africa', 15.0, 39.0, '🇪🇷'),
('EH', 'ESH', 'Western Sahara', 'Sahrawi Arab Democratic Republic', '[El Aaiún]', 'Africa', 'Northern Africa', 24.5, -13.0, '🇪🇭'),
('ES', 'ESP', 'Spain', 'Kingdom of Spain', '[Madrid]', 'Europe', 'Southern Europe', 40.0, -4.0, '🇪🇸'),
('EE', 'EST', 'Estonia', 'Republic of Estonia', '[Tallinn]', 'Europe', 'Northern Europe', 59.0, 26.0, '🇪🇪'),
('ET', 'ETH', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', '[Addis Ababa]', 'Africa', 'Eastern Africa', 8.0, 38.0, '🇪🇹'),
('FI', 'FIN', 'Finland', 'Republic of Finland', '[Helsinki]', 'Europe', 'Northern Europe', 64.0, 26.0, '🇫🇮'),
('FJ', 'FJI', 'Fiji', 'Republic of Fiji', '[Suva]', 'Oceania', 'Melanesia', -18.0, 175.0, '🇫🇯'),
('FK', 'FLK', 'Falkland Islands', 'Falkland Islands', '[Stanley]', 'Americas', 'South America', -51.75, -59.0, '🇫🇰'),
('FR', 'FRA', 'France', 'French Republic', '[Paris]', 'Europe', 'Western Europe', 46.0, 2.0, '🇫🇷'),
('FO', 'FRO', 'Faroe Islands', 'Faroe Islands', '[Tórshavn]', 'Europe', 'Northern Europe', 62.0, -7.0, '🇫🇴'),
('FM', 'FSM', 'Micronesia', 'Federated States of Micronesia', '[Palikir]', 'Oceania', 'Micronesia', 6.91666666, 158.25, '🇫🇲'),
('GA', 'GAB', 'Gabon', 'Gabonese Republic', '[Libreville]', 'Africa', 'Middle Africa', -1.0, 11.75, '🇬🇦'),
('GB', 'GBR', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', '[London]', 'Europe', 'Northern Europe', 54.0, -2.0, '🇬🇧'),
('GE', 'GEO', 'Georgia', 'Georgia', '[Tbilisi]', 'Asia', 'Western Asia', 42.0, 43.5, '🇬🇪'),
('GG', 'GGY', 'Guernsey', 'Bailiwick of Guernsey', '[St. Peter Port]', 'Europe', 'Northern Europe', 49.46666666, -2.58333333, '🇬🇬'),
('GH', 'GHA', 'Ghana', 'Republic of Ghana', '[Accra]', 'Africa', 'Western Africa', 8.0, -2.0, '🇬🇭'),
('GI', 'GIB', 'Gibraltar', 'Gibraltar', '[Gibraltar]', 'Europe', 'Southern Europe', 36.13333333, -5.35, '🇬🇮'),
('GN', 'GIN', 'Guinea', 'Republic of Guinea', '[Conakry]', 'Africa', 'Western Africa', 11.0, -10.0, '🇬🇳'),
('GP', 'GLP', 'Guadeloupe', 'Guadeloupe', '[Basse-Terre]', 'Americas', 'Caribbean', 16.25, -61.583333, '🇬🇵'),
('GM', 'GMB', 'Gambia', 'Republic of the Gambia', '[Banjul]', 'Africa', 'Western Africa', 13.46666666, -16.56666666, '🇬🇲'),
('GW', 'GNB', 'Guinea-Bissau', 'Republic of Guinea-Bissau', '[Bissau]', 'Africa', 'Western Africa', 12.0, -15.0, '🇬🇼'),
('GQ', 'GNQ', 'Equatorial Guinea', 'Republic of Equatorial Guinea', '[Malabo]', 'Africa', 'Middle Africa', 2.0, 10.0, '🇬🇶'),
('GR', 'GRC', 'Greece', 'Hellenic Republic', '[Athens]', 'Europe', 'Southern Europe', 39.0, 22.0, '🇬🇷'),
('GD', 'GRD', 'Grenada', 'Grenada', '[St. George''s]', 'Americas', 'Caribbean', 12.11666666, -61.66666666, '🇬🇩'),
('GL', 'GRL', 'Greenland', 'Greenland', '[Nuuk]', 'Americas', 'North America', 72.0, -40.0, '🇬🇱'),
('GT', 'GTM', 'Guatemala', 'Republic of Guatemala', '[Guatemala City]', 'Americas', 'Central America', 15.5, -90.25, '🇬🇹'),
('GF', 'GUF', 'French Guiana', 'Guiana', '[Cayenne]', 'Americas', 'South America', 4.0, -53.0, '🇬🇫'),
('GU', 'GUM', 'Guam', 'Guam', '[Hagåtña]', 'Oceania', 'Micronesia', 13.46666666, 144.78333333, '🇬🇺'),
('GY', 'GUY', 'Guyana', 'Co-operative Republic of Guyana', '[Georgetown]', 'Americas', 'South America', 5.0, -59.0, '🇬🇾'),
('HK', 'HKG', 'Hong Kong', 'Hong Kong Special Administrative Region of the People''s Republic of China', '[City of Victoria]', 'Asia', 'Eastern Asia', 22.267, 114.188, '🇭🇰'),
('HM', 'HMD', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', '[]', 'Antarctic', '', -53.1, 72.51666666, '🇭🇲'),
('HN', 'HND', 'Honduras', 'Republic of Honduras', '[Tegucigalpa]', 'Americas', 'Central America', 15.0, -86.5, '🇭🇳'),
('HR', 'HRV', 'Croatia', 'Republic of Croatia', '[Zagreb]', 'Europe', 'Southeast Europe', 45.16666666, 15.5, '🇭🇷'),
('HT', 'HTI', 'Haiti', 'Republic of Haiti', '[Port-au-Prince]', 'Americas', 'Caribbean', 19.0, -72.41666666, '🇭🇹'),
('HU', 'HUN', 'Hungary', 'Hungary', '[Budapest]', 'Europe', 'Central Europe', 47.0, 20.0, '🇭🇺'),
('ID', 'IDN', 'Indonesia', 'Republic of Indonesia', '[Jakarta]', 'Asia', 'South-Eastern Asia', -5.0, 120.0, '🇮🇩'),
('IM', 'IMN', 'Isle of Man', 'Isle of Man', '[Douglas]', 'Europe', 'Northern Europe', 54.25, -4.5, '🇮🇲'),
('IN', 'IND', 'India', 'Republic of India', '[New Delhi]', 'Asia', 'Southern Asia', 20.0, 77.0, '🇮🇳'),
('IO', 'IOT', 'British Indian Ocean Territory', 'British Indian Ocean Territory', '[Diego Garcia]', 'Africa', 'Eastern Africa', -6.0, 71.5, '🇮🇴'),
('IE', 'IRL', 'Ireland', 'Republic of Ireland', '[Dublin]', 'Europe', 'Northern Europe', 53.0, -8.0, '🇮🇪'),
('IR', 'IRN', 'Iran', 'Islamic Republic of Iran', '[Tehran]', 'Asia', 'Southern Asia', 32.0, 53.0, '🇮🇷'),
('IQ', 'IRQ', 'Iraq', 'Republic of Iraq', '[Baghdad]', 'Asia', 'Western Asia', 33.0, 44.0, '🇮🇶'),
('IS', 'ISL', 'Iceland', 'Iceland', '[Reykjavik]', 'Europe', 'Northern Europe', 65.0, -18.0, '🇮🇸'),
('IL', 'ISR', 'Israel', 'State of Israel', '[Jerusalem]', 'Asia', 'Western Asia', 31.47, 35.13, '🇮🇱'),
('IT', 'ITA', 'Italy', 'Italian Republic', '[Rome]', 'Europe', 'Southern Europe', 42.83333333, 12.83333333, '🇮🇹'),
('JM', 'JAM', 'Jamaica', 'Jamaica', '[Kingston]', 'Americas', 'Caribbean', 18.25, -77.5, '🇯🇲'),
('JE', 'JEY', 'Jersey', 'Bailiwick of Jersey', '[Saint Helier]', 'Europe', 'Northern Europe', 49.25, -2.16666666, '🇯🇪'),
('JO', 'JOR', 'Jordan', 'Hashemite Kingdom of Jordan', '[Amman]', 'Asia', 'Western Asia', 31.0, 36.0, '🇯🇴'),
('JP', 'JPN', 'Japan', 'Japan', '[Tokyo]', 'Asia', 'Eastern Asia', 36.0, 138.0, '🇯🇵'),
('KZ', 'KAZ', 'Kazakhstan', 'Republic of Kazakhstan', '[Astana]', 'Asia', 'Central Asia', 48.0, 68.0, '🇰🇿'),
('KE', 'KEN', 'Kenya', 'Republic of Kenya', '[Nairobi]', 'Africa', 'Eastern Africa', 1.0, 38.0, '🇰🇪'),
('KG', 'KGZ', 'Kyrgyzstan', 'Kyrgyz Republic', '[Bishkek]', 'Asia', 'Central Asia', 41.0, 75.0, '🇰🇬'),
('KH', 'KHM', 'Cambodia', 'Kingdom of Cambodia', '[Phnom Penh]', 'Asia', 'South-Eastern Asia', 13.0, 105.0, '🇰🇭'),
('KI', 'KIR', 'Kiribati', 'Independent and Sovereign Republic of Kiribati', '[South Tarawa]', 'Oceania', 'Micronesia', 1.41666666, 173.0, '🇰🇮'),
('KN', 'KNA', 'Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevis', '[Basseterre]', 'Americas', 'Caribbean', 17.33333333, -62.75, '🇰🇳'),
('KR', 'KOR', 'South Korea', 'Republic of Korea', '[Seoul]', 'Asia', 'Eastern Asia', 37.0, 127.5, '🇰🇷'),
('XK', 'UNK', 'Kosovo', 'Republic of Kosovo', '[Pristina]', 'Europe', 'Southeast Europe', 42.666667, 21.166667, '🇽🇰'),
('KW', 'KWT', 'Kuwait', 'State of Kuwait', '[Kuwait City]', 'Asia', 'Western Asia', 29.5, 45.75, '🇰🇼'),
('LA', 'LAO', 'Laos', 'Lao People''s Democratic Republic', '[Vientiane]', 'Asia', 'South-Eastern Asia', 18.0, 105.0, '🇱🇦'),
('LB', 'LBN', 'Lebanon', 'Lebanese Republic', '[Beirut]', 'Asia', 'Western Asia', 33.83333333, 35.83333333, '🇱🇧'),
('LR', 'LBR', 'Liberia', 'Republic of Liberia', '[Monrovia]', 'Africa', 'Western Africa', 6.5, -9.5, '🇱🇷'),
('LY', 'LBY', 'Libya', 'State of Libya', '[Tripoli]', 'Africa', 'Northern Africa', 25.0, 17.0, '🇱🇾'),
('LC', 'LCA', 'Saint Lucia', 'Saint Lucia', '[Castries]', 'Americas', 'Caribbean', 13.88333333, -60.96666666, '🇱🇨'),
('LI', 'LIE', 'Liechtenstein', 'Principality of Liechtenstein', '[Vaduz]', 'Europe', 'Western Europe', 47.26666666, 9.53333333, '🇱🇮'),
('LK', 'LKA', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', '[Colombo]', 'Asia', 'Southern Asia', 7.0, 81.0, '🇱🇰'),
('LS', 'LSO', 'Lesotho', 'Kingdom of Lesotho', '[Maseru]', 'Africa', 'Southern Africa', -29.5, 28.5, '🇱🇸'),
('LT', 'LTU', 'Lithuania', 'Republic of Lithuania', '[Vilnius]', 'Europe', 'Northern Europe', 56.0, 24.0, '🇱🇹'),
('LU', 'LUX', 'Luxembourg', 'Grand Duchy of Luxembourg', '[Luxembourg]', 'Europe', 'Western Europe', 49.75, 6.16666666, '🇱🇺'),
('LV', 'LVA', 'Latvia', 'Republic of Latvia', '[Riga]', 'Europe', 'Northern Europe', 57.0, 25.0, '🇱🇻'),
('MO', 'MAC', 'Macau', 'Macao Special Administrative Region of the People''s Republic of China', '[]', 'Asia', 'Eastern Asia', 22.16666666, 113.55, '🇲🇴'),
('MF', 'MAF', 'Saint Martin', 'Saint Martin', '[Marigot]', 'Americas', 'Caribbean', 18.08333333, -63.95, '🇲🇫'),
('MA', 'MAR', 'Morocco', 'Kingdom of Morocco', '[Rabat]', 'Africa', 'Northern Africa', 32.0, -5.0, '🇲🇦'),
('MC', 'MCO', 'Monaco', 'Principality of Monaco', '[Monaco]', 'Europe', 'Western Europe', 43.73333333, 7.4, '🇲🇨'),
('MD', 'MDA', 'Moldova', 'Republic of Moldova', '[Chișinău]', 'Europe', 'Eastern Europe', 47.0, 29.0, '🇲🇩'),
('MG', 'MDG', 'Madagascar', 'Republic of Madagascar', '[Antananarivo]', 'Africa', 'Eastern Africa', -20.0, 47.0, '🇲🇬'),
('MV', 'MDV', 'Maldives', 'Republic of the Maldives', '[Malé]', 'Asia', 'Southern Asia', 3.25, 73.0, '🇲🇻'),
('MX', 'MEX', 'Mexico', 'United Mexican States', '[Mexico City]', 'Americas', 'North America', 23.0, -102.0, '🇲🇽'),
('MH', 'MHL', 'Marshall Islands', 'Republic of the Marshall Islands', '[Majuro]', 'Oceania', 'Micronesia', 9.0, 168.0, '🇲🇭'),
('MK', 'MKD', 'North Macedonia', 'Republic of North Macedonia', '[Skopje]', 'Europe', 'Southeast Europe', 41.83333333, 22.0, '🇲🇰'),
('ML', 'MLI', 'Mali', 'Republic of Mali', '[Bamako]', 'Africa', 'Western Africa', 17.0, -4.0, '🇲🇱'),
('MT', 'MLT', 'Malta', 'Republic of Malta', '[Valletta]', 'Europe', 'Southern Europe', 35.83333333, 14.58333333, '🇲🇹'),
('MM', 'MMR', 'Myanmar', 'Republic of the Union of Myanmar', '[Naypyidaw]', 'Asia', 'South-Eastern Asia', 22.0, 98.0, '🇲🇲'),
('ME', 'MNE', 'Montenegro', 'Montenegro', '[Podgorica]', 'Europe', 'Southeast Europe', 42.5, 19.3, '🇲🇪'),
('MN', 'MNG', 'Mongolia', 'Mongolia', '[Ulan Bator]', 'Asia', 'Eastern Asia', 46.0, 105.0, '🇲🇳'),
('MP', 'MNP', 'Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands', '[Saipan]', 'Oceania', 'Micronesia', 15.2, 145.75, '🇲🇵'),
('MZ', 'MOZ', 'Mozambique', 'Republic of Mozambique', '[Maputo]', 'Africa', 'Eastern Africa', -18.25, 35.0, '🇲🇿'),
('MR', 'MRT', 'Mauritania', 'Islamic Republic of Mauritania', '[Nouakchott]', 'Africa', 'Western Africa', 20.0, -12.0, '🇲🇷'),
('MS', 'MSR', 'Montserrat', 'Montserrat', '[Plymouth]', 'Americas', 'Caribbean', 16.75, -62.2, '🇲🇸'),
('MQ', 'MTQ', 'Martinique', 'Martinique', '[Fort-de-France]', 'Americas', 'Caribbean', 14.666667, -61.0, '🇲🇶'),
('MU', 'MUS', 'Mauritius', 'Republic of Mauritius', '[Port Louis]', 'Africa', 'Eastern Africa', -20.28333333, 57.55, '🇲🇺'),
('MW', 'MWI', 'Malawi', 'Republic of Malawi', '[Lilongwe]', 'Africa', 'Eastern Africa', -13.5, 34.0, '🇲🇼'),
('MY', 'MYS', 'Malaysia', 'Malaysia', '[Kuala Lumpur]', 'Asia', 'South-Eastern Asia', 2.5, 112.5, '🇲🇾'),
('YT', 'MYT', 'Mayotte', 'Department of Mayotte', '[Mamoudzou]', 'Africa', 'Eastern Africa', -12.83333333, 45.16666666, '🇾🇹'),
('NA', 'NAM', 'Namibia', 'Republic of Namibia', '[Windhoek]', 'Africa', 'Southern Africa', -22.0, 17.0, '🇳🇦'),
('NC', 'NCL', 'New Caledonia', 'New Caledonia', '[Nouméa]', 'Oceania', 'Melanesia', -21.5, 165.5, '🇳🇨'),
('NE', 'NER', 'Niger', 'Republic of Niger', '[Niamey]', 'Africa', 'Western Africa', 16.0, 8.0, '🇳🇪'),
('NF', 'NFK', 'Norfolk Island', 'Territory of Norfolk Island', '[Kingston]', 'Oceania', 'Australia and New Zealand', -29.03333333, 167.95, '🇳🇫'),
('NG', 'NGA', 'Nigeria', 'Federal Republic of Nigeria', '[Abuja]', 'Africa', 'Western Africa', 10.0, 8.0, '🇳🇬'),
('NI', 'NIC', 'Nicaragua', 'Republic of Nicaragua', '[Managua]', 'Americas', 'Central America', 13.0, -85.0, '🇳🇮'),
('NU', 'NIU', 'Niue', 'Niue', '[Alofi]', 'Oceania', 'Polynesia', -19.03333333, -169.86666666, '🇳🇺'),
('NL', 'NLD', 'Netherlands', 'Kingdom of the Netherlands', '[Amsterdam]', 'Europe', 'Western Europe', 52.5, 5.75, '🇳🇱'),
('NO', 'NOR', 'Norway', 'Kingdom of Norway', '[Oslo]', 'Europe', 'Northern Europe', 62.0, 10.0, '🇳🇴'),
('NP', 'NPL', 'Nepal', 'Federal Democratic Republic of Nepal', '[Kathmandu]', 'Asia', 'Southern Asia', 28.0, 84.0, '🇳🇵'),
('NR', 'NRU', 'Nauru', 'Republic of Nauru', '[Yaren]', 'Oceania', 'Micronesia', -0.53333333, 166.91666666, '🇳🇷'),
('NZ', 'NZL', 'New Zealand', 'New Zealand', '[Wellington]', 'Oceania', 'Australia and New Zealand', -41.0, 174.0, '🇳🇿'),
('OM', 'OMN', 'Oman', 'Sultanate of Oman', '[Muscat]', 'Asia', 'Western Asia', 21.0, 57.0, '🇴🇲'),
('PK', 'PAK', 'Pakistan', 'Islamic Republic of Pakistan', '[Islamabad]', 'Asia', 'Southern Asia', 30.0, 70.0, '🇵🇰'),
('PA', 'PAN', 'Panama', 'Republic of Panama', '[Panama City]', 'Americas', 'Central America', 9.0, -80.0, '🇵🇦'),
('PN', 'PCN', 'Pitcairn Islands', 'Pitcairn Group of Islands', '[Adamstown]', 'Oceania', 'Polynesia', -25.06666666, -130.1, '🇵🇳'),
('PE', 'PER', 'Peru', 'Republic of Peru', '[Lima]', 'Americas', 'South America', -10.0, -76.0, '🇵🇪'),
('PH', 'PHL', 'Philippines', 'Republic of the Philippines', '[Manila]', 'Asia', 'South-Eastern Asia', 13.0, 122.0, '🇵🇭'),
('PW', 'PLW', 'Palau', 'Republic of Palau', '[Ngerulmud]', 'Oceania', 'Micronesia', 7.5, 134.5, '🇵🇼'),
('PG', 'PNG', 'Papua New Guinea', 'Independent State of Papua New Guinea', '[Port Moresby]', 'Oceania', 'Melanesia', -6.0, 147.0, '🇵🇬'),
('PL', 'POL', 'Poland', 'Republic of Poland', '[Warsaw]', 'Europe', 'Central Europe', 52.0, 20.0, '🇵🇱'),
('PR', 'PRI', 'Puerto Rico', 'Commonwealth of Puerto Rico', '[San Juan]', 'Americas', 'Caribbean', 18.25, -66.5, '🇵🇷'),
('KP', 'PRK', 'North Korea', 'Democratic People''s Republic of Korea', '[Pyongyang]', 'Asia', 'Eastern Asia', 40.0, 127.0, '🇰🇵'),
('PT', 'PRT', 'Portugal', 'Portuguese Republic', '[Lisbon]', 'Europe', 'Southern Europe', 39.5, -8.0, '🇵🇹'),
('PY', 'PRY', 'Paraguay', 'Republic of Paraguay', '[Asunción]', 'Americas', 'South America', -23.0, -58.0, '🇵🇾'),
('PS', 'PSE', 'Palestine', 'State of Palestine', '[Ramallah]', 'Asia', 'Western Asia', 31.9, 35.2, '🇵🇸'),
('PF', 'PYF', 'French Polynesia', 'French Polynesia', '[Papeetē]', 'Oceania', 'Polynesia', -15.0, -140.0, '🇵🇫'),
('QA', 'QAT', 'Qatar', 'State of Qatar', '[Doha]', 'Asia', 'Western Asia', 25.5, 51.25, '🇶🇦'),
('RE', 'REU', 'Réunion', 'Réunion Island', '[Saint-Denis]', 'Africa', 'Eastern Africa', -21.15, 55.5, '🇷🇪'),
('RO', 'ROU', 'Romania', 'Romania', '[Bucharest]', 'Europe', 'Southeast Europe', 46.0, 25.0, '🇷🇴'),
('RU', 'RUS', 'Russia', 'Russian Federation', '[Moscow]', 'Europe', 'Eastern Europe', 60.0, 100.0, '🇷🇺'),
('RW', 'RWA', 'Rwanda', 'Republic of Rwanda', '[Kigali]', 'Africa', 'Eastern Africa', -2.0, 30.0, '🇷🇼'),
('SA', 'SAU', 'Saudi Arabia', 'Kingdom of Saudi Arabia', '[Riyadh]', 'Asia', 'Western Asia', 25.0, 45.0, '🇸🇦'),
('SD', 'SDN', 'Sudan', 'Republic of the Sudan', '[Khartoum]', 'Africa', 'Northern Africa', 15.0, 30.0, '🇸🇩'),
('SN', 'SEN', 'Senegal', 'Republic of Senegal', '[Dakar]', 'Africa', 'Western Africa', 14.0, -14.0, '🇸🇳'),
('SG', 'SGP', 'Singapore', 'Republic of Singapore', '[Singapore]', 'Asia', 'South-Eastern Asia', 1.36666666, 103.8, '🇸🇬'),
('GS', 'SGS', 'South Georgia', 'South Georgia and the South Sandwich Islands', '[King Edward Point]', 'Antarctic', '', -54.5, -37.0, '🇬🇸'),
('SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard og Jan Mayen', '[Longyearbyen]', 'Europe', 'Northern Europe', 78.0, 20.0, '🇸🇯'),
('SB', 'SLB', 'Solomon Islands', 'Solomon Islands', '[Honiara]', 'Oceania', 'Melanesia', -8.0, 159.0, '🇸🇧'),
('SL', 'SLE', 'Sierra Leone', 'Republic of Sierra Leone', '[Freetown]', 'Africa', 'Western Africa', 8.5, -11.5, '🇸🇱'),
('SV', 'SLV', 'El Salvador', 'Republic of El Salvador', '[San Salvador]', 'Americas', 'Central America', 13.83333333, -88.91666666, '🇸🇻'),
('SM', 'SMR', 'San Marino', 'Most Serene Republic of San Marino', '[City of San Marino]', 'Europe', 'Southern Europe', 43.76666666, 12.41666666, '🇸🇲'),
('SO', 'SOM', 'Somalia', 'Federal Republic of Somalia', '[Mogadishu]', 'Africa', 'Eastern Africa', 10.0, 49.0, '🇸🇴'),
('PM', 'SPM', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', '[Saint-Pierre]', 'Americas', 'North America', 46.83333333, -56.33333333, '🇵🇲'),
('RS', 'SRB', 'Serbia', 'Republic of Serbia', '[Belgrade]', 'Europe', 'Southeast Europe', 44.0, 21.0, '🇷🇸'),
('SS', 'SSD', 'South Sudan', 'Republic of South Sudan', '[Juba]', 'Africa', 'Middle Africa', 7.0, 30.0, '🇸🇸'),
('ST', 'STP', 'São Tomé and Príncipe', 'Democratic Republic of São Tomé and Príncipe', '[São Tomé]', 'Africa', 'Middle Africa', 1.0, 7.0, '🇸🇹'),
('SR', 'SUR', 'Suriname', 'Republic of Suriname', '[Paramaribo]', 'Americas', 'South America', 4.0, -56.0, '🇸🇷'),
('SK', 'SVK', 'Slovakia', 'Slovak Republic', '[Bratislava]', 'Europe', 'Central Europe', 48.66666666, 19.5, '🇸🇰'),
('SI', 'SVN', 'Slovenia', 'Republic of Slovenia', '[Ljubljana]', 'Europe', 'Central Europe', 46.11666666, 14.81666666, '🇸🇮'),
('SE', 'SWE', 'Sweden', 'Kingdom of Sweden', '[Stockholm]', 'Europe', 'Northern Europe', 62.0, 15.0, '🇸🇪'),
('SZ', 'SWZ', 'Eswatini', 'Kingdom of Eswatini', '[Lobamba]', 'Africa', 'Southern Africa', -26.5, 31.5, '🇸🇿'),
('SX', 'SXM', 'Sint Maarten', 'Sint Maarten', '[Philipsburg]', 'Americas', 'Caribbean', 18.033333, -63.05, '🇸🇽'),
('SC', 'SYC', 'Seychelles', 'Republic of Seychelles', '[Victoria]', 'Africa', 'Eastern Africa', -4.58333333, 55.66666666, '🇸🇨'),
('SY', 'SYR', 'Syria', 'Syrian Arab Republic', '[Damascus]', 'Asia', 'Western Asia', 35.0, 38.0, '🇸🇾'),
('TC', 'TCA', 'Turks and Caicos Islands', 'Turks and Caicos Islands', '[Cockburn Town]', 'Americas', 'Caribbean', 21.75, -71.58333333, '🇹🇨'),
('TD', 'TCD', 'Chad', 'Republic of Chad', '[N''Djamena]', 'Africa', 'Middle Africa', 15.0, 19.0, '🇹🇩'),
('TG', 'TGO', 'Togo', 'Togolese Republic', '[Lomé]', 'Africa', 'Western Africa', 8.0, 1.16666666, '🇹🇬'),
('TH', 'THA', 'Thailand', 'Kingdom of Thailand', '[Bangkok]', 'Asia', 'South-Eastern Asia', 15.0, 100.0, '🇹🇭'),
('TJ', 'TJK', 'Tajikistan', 'Republic of Tajikistan', '[Dushanbe]', 'Asia', 'Central Asia', 39.0, 71.0, '🇹🇯'),
('TK', 'TKL', 'Tokelau', 'Tokelau', '[Fakaofo]', 'Oceania', 'Polynesia', -9.0, -172.0, '🇹🇰'),
('TM', 'TKM', 'Turkmenistan', 'Turkmenistan', '[Ashgabat]', 'Asia', 'Central Asia', 40.0, 60.0, '🇹🇲'),
('TL', 'TLS', 'Timor-Leste', 'Democratic Republic of Timor-Leste', '[Dili]', 'Asia', 'South-Eastern Asia', -8.83333333, 125.91666666, '🇹🇱'),
('TO', 'TON', 'Tonga', 'Kingdom of Tonga', '[Nuku''alofa]', 'Oceania', 'Polynesia', -20.0, -175.0, '🇹🇴'),
('TT', 'TTO', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', '[Port of Spain]', 'Americas', 'Caribbean', 11.0, -61.0, '🇹🇹'),
('TN', 'TUN', 'Tunisia', 'Tunisian Republic', '[Tunis]', 'Africa', 'Northern Africa', 34.0, 9.0, '🇹🇳'),
('TR', 'TUR', 'Türkiye', 'Republic of Türkiye', '[Ankara]', 'Asia', 'Western Asia', 39.0, 35.0, '🇹🇷'),
('TV', 'TUV', 'Tuvalu', 'Tuvalu', '[Funafuti]', 'Oceania', 'Polynesia', -8.0, 178.0, '🇹🇻'),
('TW', 'TWN', 'Taiwan', 'Republic of China (Taiwan)', '[Taipei]', 'Asia', 'Eastern Asia', 23.5, 121.0, '🇹🇼'),
('TZ', 'TZA', 'Tanzania', 'United Republic of Tanzania', '[Dodoma]', 'Africa', 'Eastern Africa', -6.0, 35.0, '🇹🇿'),
('UG', 'UGA', 'Uganda', 'Republic of Uganda', '[Kampala]', 'Africa', 'Eastern Africa', 1.0, 32.0, '🇺🇬'),
('UA', 'UKR', 'Ukraine', 'Ukraine', '[Kyiv]', 'Europe', 'Eastern Europe', 49.0, 32.0, '🇺🇦'),
('UM', 'UMI', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', '[]', 'Americas', 'North America', 19.3, 166.633333, '🇺🇲'),
('UY', 'URY', 'Uruguay', 'Oriental Republic of Uruguay', '[Montevideo]', 'Americas', 'South America', -33.0, -56.0, '🇺🇾'),
('US', 'USA', 'United States', 'United States of America', '[Washington D.C.]', 'Americas', 'North America', 38.0, -97.0, '🇺🇸'),
('UZ', 'UZB', 'Uzbekistan', 'Republic of Uzbekistan', '[Tashkent]', 'Asia', 'Central Asia', 41.0, 64.0, '🇺🇿'),
('VA', 'VAT', 'Vatican City', 'Vatican City State', '[Vatican City]', 'Europe', 'Southern Europe', 41.9, 12.45, '🇻🇦'),
('VC', 'VCT', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', '[Kingstown]', 'Americas', 'Caribbean', 13.25, -61.2, '🇻🇨'),
('VE', 'VEN', 'Venezuela', 'Bolivarian Republic of Venezuela', '[Caracas]', 'Americas', 'South America', 8.0, -66.0, '🇻🇪'),
('VG', 'VGB', 'British Virgin Islands', 'Virgin Islands', '[Road Town]', 'Americas', 'Caribbean', 18.431383, -64.62305, '🇻🇬'),
('VI', 'VIR', 'United States Virgin Islands', 'Virgin Islands of the United States', '[Charlotte Amalie]', 'Americas', 'Caribbean', 18.35, -64.933333, '🇻🇮'),
('VN', 'VNM', 'Vietnam', 'Socialist Republic of Vietnam', '[Hanoi]', 'Asia', 'South-Eastern Asia', 16.16666666, 107.83333333, '🇻🇳'),
('VU', 'VUT', 'Vanuatu', 'Republic of Vanuatu', '[Port Vila]', 'Oceania', 'Melanesia', -16.0, 167.0, '🇻🇺'),
('WF', 'WLF', 'Wallis and Futuna', 'Territory of the Wallis and Futuna Islands', '[Mata-Utu]', 'Oceania', 'Polynesia', -13.3, -176.2, '🇼🇫'),
('WS', 'WSM', 'Samoa', 'Independent State of Samoa', '[Apia]', 'Oceania', 'Polynesia', -13.58333333, -172.33333333, '🇼🇸'),
('YE', 'YEM', 'Yemen', 'Republic of Yemen', '[Sana''a]', 'Asia', 'Western Asia', 15.0, 48.0, '🇾🇪'),
('ZA', 'ZAF', 'South Africa', 'Republic of South Africa', '[Pretoria, Bloemfontein, Cape Town]', 'Africa', 'Southern Africa', -29.0, 24.0, '🇿🇦'),
('ZM', 'ZMB', 'Zambia', 'Republic of Zambia', '[Lusaka]', 'Africa', 'Eastern Africa', -15.0, 30.0, '🇿🇲'),
('ZW', 'ZWE', 'Zimbabwe', 'Republic of Zimbabwe', '[Harare]', 'Africa', 'Eastern Africa', -20.0, 30.0, '🇿🇼');
